"""init

Revision ID: 2d0862496c86
Revises: 
Create Date: 2024-12-21 15:05:38.540192

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2d0862496c86"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "requests",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "cadastral_number", sa.String(), nullable=False, comment="Кадастровый номер"
        ),
        sa.Column("latitude", sa.Float(), nullable=False, comment="Широта"),
        sa.Column("longitude", sa.Float(), nullable=False, comment="Долгота"),
        sa.Column("score", sa.Float(), nullable=True, comment="Результат запроса"),
        sa.Column(
            "is_completed", sa.Boolean(), nullable=False, comment="Расчет выполнен"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_requests_id"), "requests", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_requests_id"), table_name="requests")
    op.drop_table("requests")
    # ### end Alembic commands ###
